# syntax=docker/dockerfile:1.4

FROM python:3.13.5-slim

WORKDIR /app

# 复制依赖清单
COPY requirements.txt .

# 使用 BuildKit 挂载 pip 缓存
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install -i https://mirrors.aliyun.com/pypi/simple/ -r requirements.txt

# 复制项目代码
COPY src /app/src
COPY run.py /app/run.py
COPY config.yaml /app/config.yaml
RUN mkdir -p /app/data


EXPOSE 8000
CMD ["python", "run.py", "--host", "0.0.0.0", "--port", "8000"]
